name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"   # chạy lại mỗi 6 tiếng
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%232e8fff&color_dots=%23161b22,%230a3d62,%23145da0,%231f7ae0,%232e8fff
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23ffb454&color_dots=%23161b22,%230a3d62,%23145da0,%231f7ae0,%232e8fff
            dist/github-contribution-grid-snake.gif?color_snake=%23ffb454&color_dots=%23161b22,%230a3d62,%23145da0,%231f7ae0,%232e8fff

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
