name: GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: Tizkan
          token: ${{ secrets.GH_TOKEN }}
